model:
  fc1:
    type: Linear
    args: [2, 64]
  relu1:
    type: ReLU
    args: []
  fc2:
    type: Linear
    args: [64, 32]
  relu2:
    type: ReLU
    args: []
  fc3:
    type: Linear
    args: [32, 1]
