# 0 - best attempt at v(t+1) from X(t)

# Paths, relative to /code where main.py is run
pairs_path: ../data/raw/evp_1200itr_fmt2.zarr
# pairs_path: ../data/raw/evp_1200itr_fmt2.zarr
parameters: ../configs/parameters/nn_base.yaml
results_path: ../results/nn/UKSIG2025/0/
architecture: ../configs/nn_architecture/it_2L.yaml
save_data: True

# TODO: add batch size, scaler, val frac
train_features: ['sivelv', 'siconc', 'sithic', 'sivelu', 'utau_ai', 'utau_oi', 'vtau_ai', 'vtau_oi']
#train_features: ['sivelv']
train_labels: ['sivelv']

difference_labels: False
zarr_fmt: fmt2
scale_features: True
shorten_dataset: 1000000
sequential: False
save_val: True

loss: MSELoss
optimizer: Adam
learning_rate: 0.001
epochs: 30

test_fraction: 0.1 # 