# Paths, relative to /code where main.py is run
pairs_path: ../data/intermediate/pairs_evp_120itr_12day.zarr
parameters: ../configs/parameters/nn_base.yaml
results_path: ../results/nn/base/
architecture: ../configs/nn_architecture/base.yaml

# TODO: add features, labels, batch size, scaler, val frac, test frac, epochs
train_features: ['siconc', 'sithic', 'sivelv', 'sivelu', 'utau_ai', 'utau_oi', 'vtau_ai', 'vtau_oi']
train_labels: ['sivelv']

epochs: 50
test_fraction: 0.01 # deliberately very small as test data aren't used at this stage