# Initial testing of minimum reasonable model choices

# Paths, relative to /code where main.py is run
pairs_path: ../data/intermediate/pairs_evp_120itr_12day.zarr
parameters: ../configs/parameters/nn_base.yaml
results_path: ../results/nn/it_12/1/
architecture: ../configs/nn_architecture/it_2L.yaml

# TODO: add batch size, scaler, val frac
train_features: ['siconc', 'sivelv']
train_labels: ['sivelv']

loss: MSELoss
optimizer: Adam
learning_rate: 0.001
epochs: 30

test_fraction: 0.01 # deliberately very small as test data aren't used at this stage