# Initial testing of model predicting differenced labels, testing on 1200 itr data 

# Paths, relative to /code where main.py is run
pairs_path: ../data/intermediate/pairs_evp_1200itr.zarr
parameters: ../configs/parameters/nn_base.yaml
results_path: ../results/nn/it/16/
architecture: ../configs/nn_architecture/it_3L.yaml

# TODO: add batch size, scaler, val frac
train_features: ['siconc', 'sithic', 'sivelv', 'sivelu', 'utau_ai', 'utau_oi', 'vtau_ai', 'vtau_oi']
train_labels: ['sivelv']

difference_labels: True

loss: MSELoss
optimizer: Adam
learning_rate: 0.001
epochs: 15

test_fraction: 0.01 # deliberately very small as test data aren't used at this stage